#!/usr/bin/env python3
"""Insert 4 SBAs from Birinyi Board Prep: 3 ethics + 1 cranial-anatomy."""

with open("content.js", "r") as f:
    lines = f.readlines()

sba_cranial_anatomy = [
    '{stem:"A neurosurgeon is performing a transpterygoid approach. She identifies the vidian nerve (nerve of the pterygoid canal) as a landmark. Which two nerves form the vidian nerve, and what type of fibres does each contribute?",opts:["A. The greater superficial petrosal nerve (parasympathetic) + the lesser superficial petrosal nerve (parasympathetic) — both carry secretomotor fibres to the pterygopalatine ganglion","B. The greater superficial petrosal nerve (parasympathetic) + the deep petrosal nerve (sympathetic) — the GSPN carries preganglionic parasympathetics from the facial nerve; the deep petrosal nerve carries sympathetics from the internal carotid plexus to the pterygopalatine ganglion","C. The chorda tympani (taste + parasympathetic) + the lesser petrosal nerve (parasympathetic) — both from the facial nerve; the vidian nerve is the combined parasympathetic bundle","D. The deep petrosal nerve (sensory) + the lesser superficial petrosal nerve (parasympathetic) — the deep petrosal nerve carries somatosensory afferents from the pterygopalatine ganglion","E. The greater auricular nerve (sensory) + the deep petrosal nerve (sympathetic) — sensation and vasomotor control to the parotid gland"],ans:1,exp:"Birinyi, p.184 (Ch.12 Q8): VIDIAN NERVE (nerve of pterygoid canal) = GSPN (greater superficial petrosal nerve) + DEEP PETROSAL NERVE. GSPN: preganglionic parasympathetics from the facial nerve (CN VII) via the geniculate ganglion — ultimately synapse in the pterygopalatine ganglion to provide lacrimation (lacrimal gland), nasal secretion, and palatal gland secretion. DEEP PETROSAL NERVE: emerges from the INTERNAL CAROTID PLEXUS; traverses the carotid canal; carries SYMPATHETICS that innervate the pterygopalatine ganglion (vasoconstriction to nasal mucosa). The two unite in the pterygoid canal to form the vidian nerve, which enters the pterygopalatine fossa posteriorly. Surgical landmark: the vidian nerve can be used to localise the ICA during transpterygoid approaches.",ref:"Birinyi, p.184",src_id:"birinyi-board-prep",korky:true,recall:true,topic:"cranial-anatomy"},'
]

sba_ethics = [
    '{stem:"You are performing a posterior cervical decompression. The patient presented with radiculopathy at C5/6. Closing intraoperative films show you have decompressed at C4/5. The planned level has not been treated. The patient is still under general anaesthesia. What is the most appropriate next course of action?",opts:["A. Close the wound without disclosing the wrong-level surgery; plan a revision procedure under a new consent form at a separate operation to minimise distress","B. Immediately contact risk management before taking any further surgical steps, as they must authorise the decision to proceed","C. Inform the family of the error, complete the decompression at the correct level C5/6 after obtaining their agreement, and notify the risk management team — full disclosure of surgical errors is ethically required and may reduce liability","D. Complete the decompression at the correct level C5/6 without informing the family, on the grounds that the outcome will be beneficial and avoid unnecessary upset","E. Close the wound, document the error only in the operative note (not in the discharge summary), and refer to a colleague for the definitive procedure"],ans:2,exp:"Birinyi, p.320 (Ch.20 Q7): WRONG-LEVEL SURGERY — correct response: INFORM the patient/family of the error + COMPLETE the correct procedure (if family agrees) + NOTIFY RISK MANAGEMENT. Key principles: (1) Full disclosure is ethically required and legally supported — acknowledging mistakes builds trust and may REDUCE liability. (2) Withholding information from the patient violates the duty of candour (UK: a statutory duty under NHS guidance to be open and honest when things go wrong). (3) Risk management should be contacted for advice on how to proceed, but they do NOT need to authorise surgical decisions. (4) In the UK, the duty of candour requires that patients be told when something has gone wrong, even without them asking.",ref:"Birinyi, p.320",src_id:"birinyi-board-prep",korky:true,recall:true,topic:"ethics"},',
    '{stem:"A 32-year-old man is declared brain dead following a catastrophic traumatic brain injury. He is on the organ donor register. His wife states she does not want him to donate his organs and refuses to give consent. What is the most appropriate course of action?",opts:["A. Halt the donation process — the wife is the next of kin and holds medical decision-making authority, which supersedes the donor register","B. Proceed with organ donation — the Uniform Anatomical Gift Act states that once a patient has registered as a donor, a third party cannot revoke the anatomical gift; it is nonetheless prudent to attempt to reconcile the donor\'s wishes with the family","C. Obtain a court order before proceeding, as the family\'s refusal creates legal ambiguity that cannot be resolved without judicial review","D. Contact the patient\'s parents for consent, as they take precedence over the spouse in organ donation decisions","E. Proceed only if the patient had also recorded his wishes in a written advance directive, as the donor register alone is insufficient to override family refusal"],ans:1,exp:"Birinyi, p.322 (Ch.20 Q10): ORGAN DONATION — Uniform Anatomical Gift Act: \'In the absence of an expressed, contrary indication by the donor, a person other than the donor is barred from making, amending, or revoking an anatomical gift of a donor\'s body or a part if the donor made an anatomical gift.\' Therefore, PROCEEDING WITH DONATION is the most appropriate course of action. Key: the registered donor\'s wishes are legally binding; the family has no authority to override them. However, it is always PRUDENT to attempt to reconcile the donor\'s wishes with the family\'s concerns. UK context: the UK Human Tissue Act 2004 and Organ Donation (Deemed Consent) Act 2019 (soft opt-out in England from May 2020) similarly uphold the principle that a registered donor\'s wishes are respected.",ref:"Birinyi, p.322",src_id:"birinyi-board-prep",korky:true,recall:true,topic:"ethics"},',
    '{stem:"A 3-year-old child requires an urgent blood transfusion intraoperatively following traumatic intracranial haemorrhage with haemodynamic compromise. The parents are Jehovah\'s Witnesses and have refused transfusion on religious grounds, threatening legal action if blood is given. What is the most appropriate course of action?",opts:["A. Do not transfuse the patient — parental religious autonomy must be respected in all paediatric medical decisions","B. Withhold transfusion and contact the hospital ethics committee for emergency guidance before proceeding","C. Obtain an emergency court order before transfusing — legal authorisation is required when parents formally refuse life-saving treatment for a minor","D. Proceed with transfusion after documenting the clinical indication in the notes — in life-threatening emergencies, physicians are legally and ethically required to act in the best interest of a minor, even when parents object on religious grounds","E. Seek blood product alternatives (e.g., cell salvage) and only transfuse if the patient arrests; document the family\'s wishes in the notes"],ans:3,exp:"Birinyi, p.324 (Ch.20 Q23): BLOOD TRANSFUSION IN A JW CHILD — In EMERGENT situations, physicians must ACT IN THE BEST INTEREST OF A MINOR even when parents object on religious grounds. Key legal principle: parental autonomy does NOT extend to decisions that put a child\'s life at risk. DOCUMENTATION of the clinical indication is essential. UK context: doctors are protected by the Children Act 1989 and case law (e.g., Re E 1993) — courts will almost always authorise transfusion for children when life is at risk. The distinction is critical: an adult Jehovah\'s Witness with capacity may refuse blood; a child cannot be allowed to die on the basis of their parents\' religious beliefs. The threat of legal action from the family does NOT change the correct course of action.",ref:"Birinyi, p.324",src_id:"birinyi-board-prep",korky:true,recall:true,topic:"ethics"}'
]

insertions = [
    (1445, sba_ethics),
    (931,  sba_cranial_anatomy),
]

for q_end_line, sbas in insertions:
    insert_pos = q_end_line - 1
    assert lines[insert_pos].rstrip() == ']},', f"Expected ']}},' at line {q_end_line}, got: {repr(lines[insert_pos])}"
    for sba in reversed(sbas):
        lines.insert(insert_pos, sba + "\n")

with open("content.js", "w") as f:
    f.writelines(lines)

total = sum(len(s) for _, s in insertions)
print(f"Inserted {total} SBAs.")
