#!/usr/bin/env python3
"""Insert 8 SBAs from Shaya 2nd ed top-10 pass (one per top-10 recall topic)."""

with open("content.js", "r") as f:
    lines = f.readlines()

sba_vascular_aneurysm = [
    '{stem:"A 35-year-old presents with a generalised tonic-clonic seizure. Cerebral angiography demonstrates a left frontal AVM with a nidus measuring 4.5cm, located in non-eloquent brain with superficial venous drainage. What is the Spetzler-Martin grade, and what score does each component contribute?",opts:["A. Spetzler-Martin Grade 1 — nidus <3cm contributes 1 point; non-eloquent brain adds 0; superficial drainage adds 0","B. Spetzler-Martin Grade 2 — nidus 3–6cm contributes 2 points; non-eloquent brain adds 0 points; superficial venous drainage adds 0 points; total score = 2","C. Spetzler-Martin Grade 3 — nidus 4.5cm contributes 3 points regardless of eloquence or drainage pattern","D. Spetzler-Martin Grade 4 — eloquent location automatically adds 2 points; deep drainage adds 1 further point","E. Spetzler-Martin Grade 5 — maximum grade requires nidus >6cm plus eloquent location plus deep drainage"],ans:1,exp:"Shaya 2e, p.184 (Q33): SPETZLER-MARTIN GRADING of AVMs — three components: (1) SIZE: <3cm = 1pt, 3–6cm = 2pts, >6cm = 3pts; (2) ELOQUENCE of adjacent brain: non-eloquent = 0pts, eloquent = 1pt; (3) VENOUS DRAINAGE: superficial = 0pts, deep = 1pt. For this AVM: nidus 4.5cm (3–6cm range) = 2pts; non-eloquent = 0pts; superficial drainage = 0pts → GRADE 2. Eloquent areas include: sensorimotor, language, visual cortex, thalamus, hypothalamus, internal capsule, brainstem, cerebellar peduncles, deep cerebellar nuclei.",ref:"Shaya 2e, p.184",src_id:"shaya-practice-questions",korky:true,recall:true,topic:"vascular-aneurysm"},'
]

sba_head_injury = [
    '{stem:"A 24-year-old is admitted after a road traffic collision with bilateral periorbital bruising, haemotympanum, and clear fluid draining from the nose. On day 3 he develops fever, photophobia, and neck stiffness. Which pathogen is most likely responsible and what is the typical timing of infection after basilar skull fracture?",opts:["A. Staphylococcus aureus — haematogenous seeding from skin lacerations; most common cause of early post-traumatic meningitis","B. Pseudomonas aeruginosa — gram-negative bacillus; common in penetrating head injuries involving the sinuses","C. Escherichia coli — gut flora contamination; more common in neonatal meningitis","D. Streptococcus pneumoniae — most common pathogen after basilar skull fracture; infection typically occurs within the first few days as organisms ascend through the CSF fistula","E. Haemophilus influenzae — most common cause of meningitis in unvaccinated children under 5 years; common after basilar fracture in adults"],ans:3,exp:"Shaya 2e, p.182 (Q17): After BASILAR SKULL FRACTURES, the most common pathogen is STREPTOCOCCUS PNEUMONIAE, and infection typically occurs within the first few days. The clinical scenario describes Battle\'s sign (retroauricular bruising), haemotympanum, and CSF rhinorrhoea — classical signs of a basilar skull fracture. CSF fistula creates a direct pathway for nasopharyngeal flora to ascend into the subarachnoid space. Other organisms (Haemophilus influenzae, group A Streptococcus) are less common. Prophylactic antibiotics remain controversial; most guidelines do NOT recommend routine prophylaxis as it may select resistant organisms without reducing meningitis risk.",ref:"Shaya 2e, p.182",src_id:"shaya-practice-questions",korky:true,recall:true,topic:"head-injury"},'
]

sba_neuro_onco = [
    '{stem:"A 62-year-old man with no prior neurological history presents with progressive cognitive decline and a ring-enhancing lesion on MRI. IDH-wildtype glioblastoma is confirmed on biopsy, classified as primary GBM. Regarding primary versus secondary glioblastoma, which statement is CORRECT?",opts:["A. Secondary GBM has an incidence approximately 10 times higher than primary GBM; it develops de novo in older patients without prior lower-grade glioma","B. Primary GBM presents at a mean age of 45 years, whereas secondary GBM presents in older patients aged approximately 62 years","C. Secondary GBM carries a worse prognosis with shorter median survival than primary GBM due to its higher mitotic activity","D. Primary GBM has an incidence approximately 10 times higher than secondary GBM; primary GBM presents at a mean age of 62 years; secondary GBM presents younger (mean 45 years) and carries a longer median survival; loss of heterozygosity on 10p or 10q is most common in primary GBM","E. The key genetic distinction is that primary GBM carries IDH mutation while secondary GBM is IDH-wildtype"],ans:3,exp:"Shaya 2e, p.188 (Q77): PRIMARY vs SECONDARY GBM — key distinguishing features: (1) PRIMARY GBM: incidence ~10 times HIGHER than secondary; mean age = 62 years (OLDER); more common in males; WORSE median survival. (2) SECONDARY GBM: develops from lower-grade astrocytoma/oligodendroglioma; mean age = 45 years (YOUNGER); slightly longer median survival. (3) GENETICS: loss of heterozygosity on 10p or 10q is one of the most common mutations in PRIMARY GBM. NOTE: The common exam trap is reversing the ages — primary GBM presents in OLDER patients (62 years), NOT younger. Per WHO 2021: GBM is defined as IDH-wildtype astrocytoma (not IDH-mutant).",ref:"Shaya 2e, p.188",src_id:"shaya-practice-questions",korky:true,recall:true,topic:"neuro-onco-cranial"},'
]

sba_cranial_anatomy = [
    '{stem:"A neurosurgeon planning a transcavernous approach to a parasellar lesion reviews the anatomy of the clinoidal triangle as a safe working space near the cavernous sinus. Which cranial nerves form the medial and lateral borders of the clinoidal triangle?",opts:["A. CN I (olfactory) medially and CN II (optic) laterally — the olfactory nerve passes medial to the optic nerve in the parasellar region","B. CN II (optic) medially and CN III (oculomotor) laterally — the clinoidal triangle is defined by the medial border of the optic nerve and the oculomotor nerve","C. CN III (oculomotor) medially and CN IV (trochlear) laterally — this defines the paramedial (supratrochlear) triangle","D. CN IV (trochlear) medially and CN V1 (ophthalmic division of trigeminal) laterally — both nerves run along the lateral cavernous sinus wall","E. The GSPN (greater superficial petrosal nerve) laterally and petrosal sinus medially — this defines Kawase\'s triangle"],ans:1,exp:"Shaya 2e, p.181 (Q10): CLINOIDAL TRIANGLE: defined by the MEDIAL BORDER OF THE OPTIC NERVE (CN II) medially and the OCULOMOTOR NERVE (CN III) laterally. KEY SURGICAL TRIANGLES SUMMARY: (1) Clinoidal triangle (infraoptic): CN II medially + CN III laterally. (2) Paramedial (supratrochlear) triangle: CN III medially + CN IV laterally. (3) Parkinson\'s triangle (infratrochlear): CN IV superiorly + V1 inferiorly; the anterior loop of the ICA lies in its floor. (4) Glasscocks\' triangle: bounded superiorly by GSPN; contains ICA. (5) Kawase\'s triangle: base at petrous apex; bounded by GSPN + V3.",ref:"Shaya 2e, p.181",src_id:"shaya-practice-questions",korky:true,recall:true,topic:"cranial-anatomy"},'
]

sba_degenerative_spine = [
    '{stem:"A 52-year-old presents with progressive cervical myelopathy. Plain radiographs of the cervical spine are obtained. The reporting radiologist mentions the Torg-Pavlov ratio. Which statement about this ratio is CORRECT?",opts:["A. It is the ratio of vertebral body height to disc space height; a value <0.5 indicates significant disc degeneration","B. It is the ratio of spinal canal diameter to vertebral body diameter measured on plain X-ray; a normal ratio is approximately 1.0 and a ratio <0.8 indicates cervical stenosis","C. It is a measurement derived from MRI only, comparing the sagittal spinal cord area to the subarachnoid space","D. It is a measure of lumbar foraminal stenosis on CT myelography; a ratio >1.2 indicates significant compression","E. A Torg-Pavlov ratio >0.8 indicates significant cervical stenosis correlating with risk of acute cord injury"],ans:1,exp:"Shaya 2e, p.188 (Q76): TORG-PAVLOV RATIO is a measure of CERVICAL SPINAL STENOSIS on plain X-ray. It is the ratio of: SPINAL CANAL diameter / VERTEBRAL BODY diameter (anteroposterior). NORMAL cervical spinal canal ratio ≈ 1.0. STENOTIC cervical canal = ratio <0.8. Clinical significance: a low Torg-Pavlov ratio indicates constitutional cervical stenosis which predisposes to spinal cord injury with minor trauma (stinger/burner syndrome in athletes). Limitation: the Torg-Pavlov ratio has poor positive predictive value (~12%) but excellent negative predictive value — useful for screening but not diagnosis. MRI is required for definitive stenosis assessment.",ref:"Shaya 2e, p.188",src_id:"shaya-practice-questions",korky:true,recall:true,topic:"degenerative-spine"},'
]

sba_paeds = [
    '{stem:"A neurosurgeon is asked to provide genetic counselling to two families whose children have been diagnosed with craniosynostosis syndromes. Child A has Apert syndrome and Child B has Crouzon syndrome. Which statement correctly distinguishes between these two conditions?",opts:["A. Apert syndrome is autosomal dominant while Crouzon syndrome is autosomal recessive — this genetic distinction is the primary differentiating feature","B. Crouzon syndrome is associated with bilateral coronal synostosis and Apert syndrome typically shows unicoronal synostosis — the suture pattern differentiates them","C. Patients with Apert syndrome manifest more severe mental retardation than patients with Crouzon syndrome; both syndromes are autosomal dominant and both may show bilateral coronal synostosis","D. Both syndromes carry equivalent cognitive outcomes; the distinguishing feature is the degree of midface hypoplasia which is more pronounced in Apert syndrome","E. Crouzon syndrome carries a worse cognitive prognosis due to higher intracranial pressure; Apert syndrome typically has normal intelligence"],ans:2,exp:"Shaya 2e, p.187 (Q66): APERT vs CROUZON SYNDROME — key facts: (1) Both are AUTOSOMAL DOMINANT (both may also occur as sporadic mutations) — so pattern of inheritance does NOT distinguish them. (2) Both are associated with BILATERAL CORONAL SYNOSTOSIS — so this also does NOT distinguish them. (3) KEY DISTINGUISHING FEATURE: SEVERITY OF MENTAL RETARDATION — patients with APERT syndrome have MORE SEVERE mental retardation than patients with Crouzon syndrome. Additional Apert features: syndactyly of hands and feet (acrocephalosyndactyly), midfacial hypoplasia. Crouzon: normal extremities (no syndactyly); more pronounced proptosis. Both caused by mutations in FGFR genes.",ref:"Shaya 2e, p.187",src_id:"shaya-practice-questions",korky:true,recall:true,topic:"paeds"},'
]

sba_neuro_icu = [
    '{stem:"A 42-year-old is admitted to the neuro-ICU with a severe traumatic brain injury and clinical signs of raised ICP. Intravenous mannitol 0.5g/kg is administered. Regarding the pharmacodynamics of mannitol for ICP management, which statement is CORRECT?",opts:["A. Peak ICP reduction occurs at 60 minutes after administration; duration of action is approximately 8 hours before re-dosing is required","B. Onset requires a minimum of 30 minutes; combining mannitol with furosemide reduces overall ICP-lowering efficacy due to excessive diuresis","C. Peak ICP reduction occurs in approximately 15 minutes after administration; duration of action is approximately 4 hours due to rapid renal elimination; combining mannitol with furosemide produces a GREATER ICP reduction than either agent alone","D. The peak ICP-lowering effect occurs over 24–48 hours as serum osmolarity equilibrates; furosemide should be avoided as it causes rebound cerebral oedema","E. Mannitol reduces ICP by direct cerebral vasoconstriction; peak effect at 5 minutes; no added benefit from combining with furosemide"],ans:2,exp:"Shaya 2e, p.183 (Q29): MANNITOL pharmacodynamics for ICP management: PEAK ICP REDUCTION occurs at approximately 15 MINUTES after administration. DURATION OF ACTION ≈ 4 HOURS (due to rapid renal elimination — mannitol is freely filtered at the glomerulus and poorly reabsorbed). MANNITOL + FUROSEMIDE: the combined effect on ICP reduction is GREATER than either agent alone (synergistic osmotic effect). Mechanism: (1) Immediate: plasma expansion reduces haematocrit → improved cerebral blood rheology → reduced ICP (within minutes). (2) Delayed (15–30 min): osmotic extraction of water from brain parenchyma across intact BBB. Caution: if BBB is disrupted, mannitol may accumulate in brain tissue and worsen oedema (rebound). Monitor serum osmolarity (goal <320 mOsmol/L).",ref:"Shaya 2e, p.183",src_id:"shaya-practice-questions",korky:true,recall:true,topic:"neuro-icu"},'
]

sba_functional = [
    '{stem:"A 4-year-old boy presents with 6 months of progressive pubertal development (pubic hair, testicular enlargement, advanced bone age) and intermittent episodes of uncontrollable, purposeless laughing lasting 10–30 seconds. MRI brain shows a non-enhancing pedunculated mass isointense to grey matter arising from the floor of the hypothalamus. What is the diagnosis and the classical clinical association?",opts:["A. Craniopharyngioma — suprasellar calcified cystic mass with adamantinomatous histology; presents with growth hormone deficiency and visual field loss; seizures are not a feature","B. Optic pathway glioma — associated with NF1; presents with visual deterioration; sexual precocity not typically seen","C. Hypothalamic hamartoma — sexual precocity is the most common presenting symptom; hamartomas may also cause gelastic (laughing) seizures characterised by brief episodes of uncontrollable laughter","D. Langerhans cell histiocytosis — causes central diabetes insipidus with pituitary stalk thickening; precocious puberty in advanced disease; no laughter seizures","E. Germ cell tumour (germinoma) — bifocal suprasellar and pineal; causes DI and Parinaud syndrome; pubertal changes from hCG secretion in non-germinomatous tumours"],ans:2,exp:"Shaya 2e, p.189 (Q87): HYPOTHALAMIC HAMARTOMA: SEXUAL PRECOCITY is the most common presenting symptom. GELASTIC SEIZURES (laughing seizures) are the other classical association — brief episodes of uncontrollable laughter often misdiagnosed as behavioural disturbance or absence seizures. The hamartoma is a non-neoplastic heterotopic mass of grey matter attached to the hypothalamus; isointense on MRI, non-enhancing. Mechanism of precocious puberty: the hamartoma tissue contains GnRH neurons that autonomously activate the hypothalamic-pituitary-gonadal axis. Mechanism of gelastic seizures: ictal discharge originates within the hamartoma itself. Management: medical (GnRH analogues for precocious puberty) + surgical/radiosurgery for drug-resistant seizures.",ref:"Shaya 2e, p.189",src_id:"shaya-practice-questions",korky:true,recall:true,topic:"functional"}'
]

insertions = [
    (1395, sba_functional),
    (1292, sba_neuro_icu),
    (1189, sba_paeds),
    (926,  sba_cranial_anatomy),
    (861,  sba_degenerative_spine),
    (487,  sba_neuro_onco),
    (304,  sba_head_injury),
    (205,  sba_vascular_aneurysm),
]

for q_end_line, sbas in insertions:
    insert_pos = q_end_line - 1
    assert lines[insert_pos].rstrip() == ']},', f"Expected ']}},' at line {q_end_line}, got: {repr(lines[insert_pos])}"
    for sba in reversed(sbas):
        lines.insert(insert_pos, sba + "\n")

with open("content.js", "w") as f:
    f.writelines(lines)

total = sum(len(s) for _, s in insertions)
print(f"Inserted {total} SBAs.")
