#!/usr/bin/env python3
"""Insert 4 SBAs from A&C Section 7C (Critical Care, pp.401-417)."""

with open("content.js", "r") as f:
    lines = f.readlines()

sba_neuro_icu = [
    '{stem:"A 28-year-old with severe traumatic brain injury and clinically suspected raised ICP requires emergency induction for intubation. The anaesthetic team asks which agent is most appropriate to minimise cerebral blood flow and reduce intracranial pressure. Which statement is correct?",opts:["A. Ketamine — maintains haemodynamic stability and does not alter cerebral blood flow; suitable for induction in raised ICP","B. Halothane — all volatile anaesthetics reduce cerebral metabolic rate; halothane is preferred as it produces the smallest increase in CBF among volatile agents","C. Isoflurane — the most ICP-reducing of all volatile anaesthetics; at high doses it can be used safely in severe intracranial hypertension","D. Etomidate — has no significant haemodynamic effect on CBF or ICP; adrenal suppression only occurs with prolonged infusion, not single-dose induction","E. Thiopental — short-acting barbiturate that reduces both CBF and CMRO2; the CMRO2 reduction exceeds the CBF reduction; suitable for neuroprotective induction in raised ICP"],ans:4,exp:"Alleyne/Citow 3e, p.401: THIOPENTAL (correct): rapidly crosses the BBB and reduces both CMRO2 and CBF; importantly, the CMRO2 reduction exceeds the CBF reduction — suitable for neuroprotective induction. KETAMINE (wrong): INCREASES cerebral blood flow, cerebral oxygen consumption, AND ICP — contraindicated in raised ICP. VOLATILE AGENTS (wrong): all inhalational anaesthetics reduce metabolic rate BUT increase CBF — net effect may raise ICP. Of volatile agents, ISOFLURANE increases CBF the LEAST (not halothane). ETOMIDATE (wrong): adrenal suppression occurs even after a single induction dose (not just with prolonged infusion) — a key clinical caution.",ref:"Alleyne/Citow 3e, p.401",src_id:"alleyne-board-review",korky:true,recall:true,topic:"neuro-icu"},',
    '{stem:"A 52-year-old is sedated and ventilated in the neuro-ICU following a large subarachnoid haemorrhage. On day 3 he abruptly develops bradycardia, a rising serum triglyceride, and elevated creatine kinase. Arterial blood gas shows severe lactic acidosis. What is the most likely diagnosis and immediate management?",opts:["A. Sepsis with multi-organ failure — obtain blood cultures and start broad-spectrum antibiotics with fluid resuscitation","B. Neurogenic cardiac dysfunction (Takotsubo cardiomyopathy) — beta-blockade and avoidance of catecholamines","C. Propofol infusion syndrome — abrupt onset of bradycardia, heart failure, lactic acidosis, hyperlipidaemia, and rhabdomyolysis occurring with high-dose or prolonged propofol infusion; immediate discontinuation of propofol is required","D. ST-elevation myocardial infarction — urgent ECG and troponin; cardiology review for primary PCI","E. Hypertriglyceridaemia from total parenteral nutrition fat emulsion — reduce infusion rate and add insulin"],ans:2,exp:"Alleyne/Citow 3e, p.416: PROPOFOL INFUSION SYNDROME: triad of bradycardia, hyperlipidaemia, and rhabdomyolysis in a ventilated neuro-ICU patient is consistent with this diagnosis. Full picture includes: abrupt onset heart failure, bradycardia, LACTIC ACIDOSIS, hyperlipidaemia, and rhabdomyolysis. Typically occurs in high-dose or prolonged propofol infusions. KEY: the most appropriate next step is IMMEDIATE DISCONTINUATION of propofol. Renal dialysis may subsequently become necessary. The mechanism involves impaired mitochondrial fatty acid oxidation. Prevention: limit propofol to <4 mg/kg/hr; monitor for triglycerides and lactate during prolonged use.",ref:"Alleyne/Citow 3e, p.416",src_id:"alleyne-board-review",korky:true,recall:true,topic:"neuro-icu"},',
    '{stem:"A 68-year-old with a large basilar artery territory infarct is intubated in the neuro-ICU. The ventilator waveform shows a recurring pattern of a few rapid deep breaths followed by a 2-3 second pause at the point of full inspiration. Which breathing pattern is this and where is the lesion?",opts:["A. Cheyne-Stokes respiration — waxing and waning hyperpnea regularly alternating with apneic periods; due to cerebral hemisphere lesion causing brainstem hypersensitivity to CO2","B. Central neurogenic hyperventilation — continuously increasing rate and depth leading to respiratory alkalosis; lesions of the lower midbrain and upper pontine tegmentum","C. Biot (ataxic) breathing — irregular interruptions; each breath varies in rate and depth; dorsomedial medullary lesions","D. Apneustic breathing — a few rapid deep breaths alternating with apneic cycles with a 2-3 second pause in full inspiration; caused by basilar artery occlusion or low pontine lesions","E. Cluster breathing — brief clusters followed by long pauses; associated with high cervical cord or medullary compression"],ans:3,exp:"Alleyne/Citow 3e, p.417: BRAINSTEM RESPIRATORY PATTERNS — four key patterns: (1) CHEYNE-STOKES: waxing and waning hyperpnea regularly alternating with SHORTER apneic periods; thought to be due to isolation of brainstem respiratory centres from the cerebrum (brainstem becomes more sensitive to CO2). (2) CENTRAL NEUROGENIC HYPERVENTILATION: increase in rate AND depth of respiration leading to respiratory ALKALOSIS; lesions of lower midbrain/upper pontine tegmentum. (3) APNEUSTIC BREATHING: few rapid deep breaths alternating with apneic cycles with 2-3 second pause IN FULL INSPIRATION — caused by BASILAR ARTERY OCCLUSION or low pontine lesions. (4) BIOT (ATAXIC) breathing: irregularly interrupted; each breath varies in rate and depth; DORSOMEDIAL MEDULLA lesions. The described pattern (pause in full inspiration) = apneustic breathing.",ref:"Alleyne/Citow 3e, p.417",src_id:"alleyne-board-review",korky:true,recall:true,topic:"neuro-icu"},',
    '{stem:"A 45-year-old with a rapidly expanding extradural haematoma develops progressive obtundation. On examination his BP is 220/100 mmHg and pulse is 38 bpm. What is the mechanism of the hypertension, and what constitutes the full triad?",opts:["A. Pain and sympathetic catecholamine surge secondary to raised ICP causing tachycardia and hypertension","B. Increased sympathetic outflow in response to rising ICP raises systemic arterial pressure in an attempt to maintain CPP; bradycardia occurs as arterial pressure rises; together with abnormal breathing this constitutes Cushing\'s triad","C. Parasympathetic activation in response to raised ICP directly elevates arterial pressure and causes bradycardia via increased vagal tone","D. ICP directly compresses the vasomotor centre, stimulating acetylcholine-mediated peripheral vasoconstriction","E. Hypertension is a reflex response to neurogenic vasodilatation; bradycardia results from baroreceptor activation in an otherwise healthy heart"],ans:1,exp:"Alleyne/Citow 3e, p.417: CUSHING\'S REFLEX: rise in systemic arterial pressure due to INCREASED SYMPATHETIC ACTIVITY (NOT parasympathetic — C is false) in response to rising ICP. Mechanism: Cushing was the first neurosurgeon to recognise that raised ICP compromises cerebral blood flow; the vasomotor centre responds by increasing sympathetic outflow to raise MAP and maintain CPP. As systemic arterial pressure rises, BRADYCARDIA may occur via baroreceptor reflex (NOT tachycardia — A is false). CUSHING\'S TRIAD = HYPERTENSION + BRADYCARDIA + ABNORMAL BREATHING. Clinical importance: Cushing\'s triad is a pre-terminal sign of severe intracranial hypertension indicating brainstem herniation — requires immediate intervention.",ref:"Alleyne/Citow 3e, p.417",src_id:"alleyne-board-review",korky:true,recall:true,topic:"neuro-icu"}'
]

insertions = [
    (1288, sba_neuro_icu),
]

for q_end_line, sbas in insertions:
    insert_pos = q_end_line - 1
    assert lines[insert_pos].rstrip() == ']},', f"Expected ']}},' at line {q_end_line}, got: {repr(lines[insert_pos])}"
    for sba in reversed(sbas):
        lines.insert(insert_pos, sba + "\n")

with open("content.js", "w") as f:
    f.writelines(lines)

total = sum(len(s) for _, s in insertions)
print(f"Inserted {total} SBAs.")
